# READ DATA

In [100]:
import numpy as np
import pandas as pd 
import seaborn as sns 

factor = pd.read_csv("../factors.csv")
report = pd.read_csv("../report.csv")

In [101]:
product_num = len(factor["product_id"].unique())
order_num = len(factor["order_id"].unique())
products = factor.drop_duplicates(subset=["product_id"])
departments = factor.drop_duplicates(subset=["department_id"])
prd_dept = factor.drop_duplicates(subset=["product_id"])

print("productNum:" , product_num)
print("orderNum:",order_num)

productNum: 39123
orderNum: 131209

In [102]:
products = products[['product_id','product_name']]
products

         product_id                                   product_name
0             49302                               Bulgarian Yogurt
1             11109  Organic 4% Milk Fat Whole Milk Cottage Cheese
2             10246                          Organic Celery Hearts
3             49683                                 Cucumber Kirby
4             43633           Lightly Smoked Sardines in Olive Oil
...             ...                                            ...
1384121        1528                               Sprinkles Decors
1384146       47935               Classic Original Lip Balm SPF 12
1384147        9491                         Goats Milk & Chai Soap
1384160       16380                               Stevia Sweetener
1384522       38900              Plain Golden Toasted Bread Crumbs

[39123 rows x 2 columns]

In [103]:
departments = departments[['department_id','department_name']]
departments

     department_id  department_name
0               16       dairy eggs
2                4          produce
4               15     canned goods
9                7        beverages
13              20             deli
16              19           snacks
18              13           pantry
21               1           frozen
41              12     meat seafood
49              17        household
74               3           bakery
76              11    personal care
84               9  dry goods pasta
118             18           babies
120             21          missing
121              2            other
145             14        breakfast
166              6    international
369              5          alcohol
527             10             bulk
690              8             pets

In [104]:
prd_dept = prd_dept[['product_id','department_id','department_name']]
prd_dept

         product_id  department_id department_name
0             49302             16      dairy eggs
1             11109             16      dairy eggs
2             10246              4         produce
3             49683              4         produce
4             43633             15    canned goods
...             ...            ...             ...
1384121        1528             13          pantry
1384146       47935             11   personal care
1384147        9491             11   personal care
1384160       16380             13          pantry
1384522       38900             13          pantry

[39123 rows x 3 columns]

In [105]:
factor.count()
factor.head()

,order_id,product_id,product_name,department_id,department_name
0,1,49302,Bulgarian Yogurt,16,dairy eggs
1,1,11109,Organic 4% Milk Fat Whole Milk Cottage Cheese,16,dairy eggs
2,1,10246,Organic Celery Hearts,4,produce
3,1,49683,Cucumber Kirby,4,produce
4,1,43633,Lightly Smoked Sardines in Olive Oil,15,canned goods

# PART A.1

In [106]:
factor1 = factor[['order_id','product_id']]
joined = pd.merge(factor1,factor1, on="order_id", how="inner")

In [107]:
solid = joined.drop(['order_id'],axis=1)
counted = solid.groupby(['product_id_x', 'product_id_y']).size().reset_index(name='count')
df = counted[counted['product_id_x'] != counted['product_id_y']]

In [108]:
df['support'] = df['count']/order_num
df = df[df['support'] > 0.003]

C:\Users\Ata\AppData\Local\Temp\ipykernel_2076\659519033.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['support'] = df['count']/order_num

In [109]:
df

          product_id_x  product_id_y  count   support
476298            2295         15290    396  0.003018
963534            4605         21903    544  0.004146
964134            4605         24852   1071  0.008163
964419            4605         26209    496  0.003780
968998            4605         47626    747  0.005693
...                ...           ...    ...       ...
11356281         49235         13176    490  0.003734
11358365         49235         24852    500  0.003811
11458461         49683         24852    743  0.005663
11462224         49683         47626    424  0.003231
11462245         49683         47766    403  0.003071

[660 rows x 4 columns]

In [110]:
each_product = factor.drop(['order_id'],axis=1).groupby(['product_id']).size().reset_index(name='count')
df['confidence'] = df['count'] / df['product_id_x'].map(each_product.set_index('product_id')['count'])
df = df[df['confidence'] > 0.25]
df.reset_index()

       index  product_id_x  product_id_y  count   support  confidence
0     476298          2295         15290    396  0.003018    0.339623
1     964134          4605         24852   1071  0.008163    0.284689
2    1034677          4920         24852   1162  0.008856    0.286277
3    1097777          5077         24852    628  0.004786    0.273281
4    1198680          5450         24852    865  0.006593    0.278762
5    1324176          5876         13176   1067  0.008132    0.304422
6    1825860          8174         13176    725  0.005526    0.366162
7    1862237          8277         13176    687  0.005236    0.305062
8    1893548          8424         24852    925  0.007050    0.315484
9    2045824          9076         24852    716  0.005457    0.308222
10   2118187          9387         24852    434  0.003308    0.314721
11   2221231          9839         13176    525  0.004001    0.317604
12   2407173         10749         13176    629  0.004794    0.262850
13   2629173         11777         24852    439  0.003346    0.294039
14   3451218         15290         24852    487  0.003712    0.261266
15   3737118         16759         13176    465  0.003544    0.266935
16   3754200         16797         24852   1948  0.014847    0.299969
17   4150468         18465         13176    445  0.003392    0.251839
18   4301001         19057         13176    973  0.007416    0.336562
19   4523296         20114         26209    547  0.004169    0.288046
20   4749321         21137         13176   3074  0.023428    0.282174
21   4997288         22035         13176    587  0.004474    0.294531
22   4998275         22035         21137    515  0.003925    0.258404
23   5158950         22825         13176    604  0.004603    0.319070
24   5160075         22825         21137    478  0.003643    0.252509
25   5488702         24184         24852    838  0.006387    0.288468
26   5874664         25890         24852    586  0.004466    0.280651
27   5959466         26209         47626   1595  0.012156    0.264379
28   6179680         27156         13176    412  0.003140    0.261421
29   6281606         27521         13176    454  0.003460    0.257808
30   6393465         27966         13176   1780  0.013566    0.320952
31   6395501         27966         21137   1670  0.012728    0.301118
32   6444108         28199         24852    466  0.003552    0.315291
33   6453177         28204         24852   1210  0.009222    0.371508
34   6590116         28842         26209    558  0.004253    0.290625
35   6743130         29487         24852    572  0.004359    0.292883
36   6925124         30391         13176   1268  0.009664    0.274875
37   7237134         31717         26209   1007  0.007675    0.285593
38   8009077         34969         24852    594  0.004527    0.265891
39   8091716         35221         44632    505  0.003849    0.256867
40   8254586         35951         13176    612  0.004664    0.281250
41   8617612         37646         13176    810  0.006173    0.288359
42   9003735         39275         21137   1269  0.009672    0.255538
43   9140576         39877         13176    650  0.004954    0.278134
44   9158494         39928         13176    654  0.004984    0.347872
45   9159591         39928         21137    517  0.003940    0.275000
46   9590024         41787         24852    466  0.003552    0.386081
47   9624678         41950         13176    635  0.004840    0.250197
48  10073647         43961         24852    646  0.004923    0.262602
49  10372707         45066         24852   1231  0.009382    0.346663
50  10783090         46906         24852    402  0.003064    0.263261
51  10847916         47144         24852    437  0.003331    0.298294
52  10869690         47209         13176   2420  0.018444    0.331825
53  10960580         47626         24852   2158  0.016447    0.265274
54  11007725         47766         24852   2216  0.016889    0.299096
55  11458461         49683         24852    743  0.005663    0.307915

In [111]:
df1 = df
df1 = pd.merge(df1, products , left_on="product_id_x" , right_on= "product_id" , how= 'inner')
df1.drop(['product_id'],axis = 1,inplace=True)
df1 = pd.merge(df1, products , left_on="product_id_y" , right_on= "product_id" , how= 'inner')
df1.drop(['product_id','count'],axis = 1,inplace=True)
df1 = df1.rename(columns={'product_id_x': 'product_id_1', 'product_id_y' : 'product_id_2' ,'product_name_x' : 'product_name_1','product_name_y':'product_name_2'})
df1 = df1[['product_id_1','product_id_2','product_name_1','product_name_2','confidence','support']]
df1

,product_id_1,product_id_2,product_name_1,product_name_2,confidence,support
0,2295,15290,Yellow Bell Pepper,Orange Bell Pepper,0.339623,0.003018
1,4605,24852,Yellow Onions,Banana,0.284689,0.008163
2,4920,24852,Seedless Red Grapes,Banana,0.286277,0.008856
3,5077,24852,100% Whole Wheat Bread,Banana,0.273281,0.004786
4,5450,24852,Small Hass Avocado,Banana,0.278762,0.006593
5,5876,13176,Organic Lemon,Bag of Organic Bananas,0.304422,0.008132
6,8174,13176,Organic Navel Orange,Bag of Organic Bananas,0.366162,0.005526
7,8277,13176,Apple Honeycrisp Organic,Bag of Organic Bananas,0.305062,0.005236
8,8424,24852,Broccoli Crown,Banana,0.315484,0.007050
9,9076,24852,Blueberries,Banana,0.308222,0.005457
10,9387,24852,Granny Smith Apples,Banana,0.314721,0.003308
11,9839,13176,Organic Broccoli,Bag of Organic Bananas,0.317604,0.004001
12,10749,13176,Organic Red Bell Pepper,Bag of Organic Bananas,0.262850,0.004794
13,11777,24852,Red Raspberries,Banana,0.294039,0.003346
14,15290,24852,Orange Bell Pepper,Banana,0.261266,0.003712
15,16759,13176,Organic Carrot Bunch,Bag of Organic Bananas,0.266935,0.003544
16,16797,24852,Strawberries,Banana,0.299969,0.014847
17,18465,13176,Organic Grade A Free Range Large Brown Eggs,Bag of Organic Bananas,0.251839,0.003392
18,19057,13176,Organic Large Extra Fancy Fuji Apple,Bag of Organic Bananas,0.336562,0.007416
19,20114,26209,Jalapeno Peppers,Limes,0.288046,0.004169
20,21137,13176,Organic Strawberries,Bag of Organic Bananas,0.282174,0.023428
21,22035,13176,Organic Whole String Cheese,Bag of Organic Bananas,0.294531,0.004474
22,22035,21137,Organic Whole String Cheese,Organic Strawberries,0.258404,0.003925
23,22825,13176,Organic D'Anjou Pears,Bag of Organic Bananas,0.319070,0.004603
24,22825,21137,Organic D'Anjou Pears,Organic Strawberries,0.252509,0.003643
25,24184,24852,Red Peppers,Banana,0.288468,0.006387
26,25890,24852,Boneless Skinless Chicken Breasts,Banana,0.280651,0.004466
27,26209,47626,Limes,Large Lemon,0.264379,0.012156
28,27156,13176,Organic Black Beans,Bag of Organic Bananas,0.261421,0.003140
29,27521,13176,Organic Lacinato (Dinosaur) Kale,Bag of Organic Bananas,0.257808,0.003460
30,27966,13176,Organic Raspberries,Bag of Organic Bananas,0.320952,0.013566
31,27966,21137,Organic Raspberries,Organic Strawberries,0.301118,0.012728
32,28199,24852,"Clementines, Bag",Banana,0.315291,0.003552
33,28204,24852,Organic Fuji Apple,Banana,0.371508,0.009222
34,28842,26209,Bunched Cilantro,Limes,0.290625,0.004253
35,29487,24852,Roma Tomato,Banana,0.292883,0.004359
36,30391,13176,Organic Cucumber,Bag of Organic Bananas,0.274875,0.009664
37,31717,26209,Organic Cilantro,Limes,0.285593,0.007675
38,34969,24852,Red Vine Tomato,Banana,0.265891,0.004527
39,35221,44632,Lime Sparkling Water,Sparkling Water Grapefruit,0.256867,0.003849
40,35951,13176,Organic Unsweetened Almond Milk,Bag of Organic Bananas,0.281250,0.004664
41,37646,13176,Organic Gala Apples,Bag of Organic Bananas,0.288359,0.006173
42,39275,21137,Organic Blueberries,Organic Strawberries,0.255538,0.009672
43,39877,13176,Organic Granny Smith Apple,Bag of Organic Bananas,0.278134,0.004954
44,39928,13176,Organic Kiwi,Bag of Organic Bananas,0.347872,0.004984
45,39928,21137,Organic Kiwi,Organic Strawberries,0.275000,0.003940
46,41787,24852,Bartlett Pears,Banana,0.386081,0.003552
47,41950,13176,Organic Tomato Cluster,Bag of Organic Bananas,0.250197,0.004840
48,43961,24852,Organic Peeled Whole Baby Carrots,Banana,0.262602,0.004923
49,45066,24852,Honeycrisp Apple,Banana,0.346663,0.009382
50,46906,24852,Grape White/Green Seedless,Banana,0.263261,0.003064
51,47144,24852,Unsweetened Original Almond Breeze Almond Milk,Banana,0.298294,0.003331
52,47209,13176,Organic Hass Avocado,Bag of Organic Bananas,0.331825,0.018444
53,47626,24852,Large Lemon,Banana,0.265274,0.016447
54,47766,24852,Organic Avocado,Banana,0.299096,0.016889
55,49683,24852,Cucumber Kirby,Banana,0.307915,0.005663

In [112]:
df1.to_csv('A1.csv')

# PART A.2

In [113]:
factor.head()

,order_id,product_id,product_name,department_id,department_name
0,1,49302,Bulgarian Yogurt,16,dairy eggs
1,1,11109,Organic 4% Milk Fat Whole Milk Cottage Cheese,16,dairy eggs
2,1,10246,Organic Celery Hearts,4,produce
3,1,49683,Cucumber Kirby,4,produce
4,1,43633,Lightly Smoked Sardines in Olive Oil,15,canned goods

In [114]:
factor1 = factor[['order_id','department_id']]
joined = pd.merge(factor1,factor1, on="order_id", how="inner")
joined

          order_id  department_id_x  department_id_y
0                1               16               16
1                1               16               16
2                1               16                4
3                1               16                4
4                1               16               15
...            ...              ...              ...
22868452   3421070               13               13
22868453   3421070               13                4
22868454   3421070                4               16
22868455   3421070                4               13
22868456   3421070                4                4

[22868457 rows x 3 columns]

In [115]:
unique_pair = joined.groupby(['order_id','department_id_x', 'department_id_y']).size().reset_index(name='count')
solid= unique_pair.drop(['order_id','count'],axis=1)
df = solid.groupby(['department_id_x', 'department_id_y']).size().reset_index(name='count')
df

     department_id_x  department_id_y  count
0                  1                1  51071
1                  1                2    826
2                  1                3  18560
3                  1                4  41264
4                  1                5   1038
..               ...              ...    ...
436               21               17   1177
437               21               18    612
438               21               19   3878
439               21               20   2373
440               21               21   6933

[441 rows x 3 columns]

In [116]:
df['support'] = df['count']/order_num
df = df[df['support'] > 0.003]

In [117]:
df

     department_id_x  department_id_y  count   support
0                  1                1  51071  0.389234
1                  1                2    826  0.006295
2                  1                3  18560  0.141454
3                  1                4  41264  0.314491
4                  1                5   1038  0.007911
..               ...              ...    ...       ...
436               21               17   1177  0.008970
437               21               18    612  0.004664
438               21               19   3878  0.029556
439               21               20   2373  0.018086
440               21               21   6933  0.052839

[387 rows x 4 columns]

In [118]:
each_department = factor.drop(['order_id'],axis=1).groupby(['department_id']).size().reset_index(name='count')
df['confidence'] = df['count'] / df['department_id_x'].map(each_department.set_index('department_id')['count'])
df = df[df['confidence'] > 0.25]
df.reset_index()

C:\Users\Ata\AppData\Local\Temp\ipykernel_2076\388991405.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['confidence'] = df['count'] / df['department_id_x'].map(each_department.set_index('department_id')['count'])

     index  department_id_x  department_id_y  count   support  confidence
0        0                1                1  51071  0.389234    0.508544
1        3                1                4  41264  0.314491    0.410890
2        6                1                7  26707  0.203545    0.265937
3       15                1               16  39403  0.300307    0.392359
4       18                1               19  27458  0.209269    0.273415
..     ...              ...              ...    ...       ...         ...
136    434               21               15   2106  0.016051    0.255242
137    435               21               16   5498  0.041903    0.666343
138    438               21               19   3878  0.029556    0.470004
139    439               21               20   2373  0.018086    0.287602
140    440               21               21   6933  0.052839    0.840262

[141 rows x 6 columns]

In [119]:
df2 = df
df2 = pd.merge(df2, departments , left_on="department_id_x" , right_on= "department_id" , how= 'inner')
df2.drop(['department_id'],axis = 1,inplace=True)
df2 = pd.merge(df2, departments , left_on="department_id_y" , right_on= "department_id" , how= 'inner')
df2.drop(['department_id','count'],axis = 1,inplace=True)
df2 = df2.rename(columns={'department_id_x': 'department_id_1', 'department_id_y' : 'department_id_2' ,'department_name_x' : 'department_name_1','department_name_y':'department_name_2'})
df2 = df2[['department_id_1','department_id_2','department_name_1','department_name_2','confidence','support']]
df2

,department_id_1,department_id_2,department_name_1,department_name_2,confidence,support
0,1,1,frozen,frozen,0.508544,0.389234
1,1,4,frozen,produce,0.410890,0.314491
2,1,7,frozen,beverages,0.265937,0.203545
3,1,16,frozen,dairy eggs,0.392359,0.300307
4,1,19,frozen,snacks,0.273415,0.209269
...,...,...,...,...,...,...
136,21,15,missing,canned goods,0.255242,0.016051
137,21,16,missing,dairy eggs,0.666343,0.041903
138,21,19,missing,snacks,0.470004,0.029556
139,21,20,missing,deli,0.287602,0.018086
140,21,21,missing,missing,0.840262,0.052839

In [120]:
df2.to_csv('A2.csv')

# PART B

In [121]:
df1
df3 = df1
df3 = pd.merge(df3, prd_dept , left_on="product_id_1" , right_on= "product_id" , how= 'inner')
df3.drop(['product_id'],axis = 1,inplace=True)
df3 = pd.merge(df3, prd_dept , left_on="product_id_2" , right_on= "product_id" , how= 'inner')
df3.drop(['product_id'],axis = 1,inplace=True)
df3 = df3[df3['department_id_x'] == df3['department_id_y']].reset_index()
df3.drop(['index','department_id_y','department_name_y'],axis=1,inplace=True)
df3.rename(columns={'department_id_x':'depatment_id','department_name_x' : 'department_name' }, inplace=True)
df3 = df3[['depatment_id','department_name','product_id_1','product_id_2','product_name_1','product_name_2','confidence','support']]
df3

,depatment_id,department_name,product_id_1,product_id_2,product_name_1,product_name_2,confidence,support
0,4,produce,2295,15290,Yellow Bell Pepper,Orange Bell Pepper,0.339623,0.003018
1,4,produce,4605,24852,Yellow Onions,Banana,0.284689,0.008163
2,4,produce,4920,24852,Seedless Red Grapes,Banana,0.286277,0.008856
3,4,produce,5450,24852,Small Hass Avocado,Banana,0.278762,0.006593
4,4,produce,5876,13176,Organic Lemon,Bag of Organic Bananas,0.304422,0.008132
5,4,produce,8174,13176,Organic Navel Orange,Bag of Organic Bananas,0.366162,0.005526
6,4,produce,8277,13176,Apple Honeycrisp Organic,Bag of Organic Bananas,0.305062,0.005236
7,4,produce,8424,24852,Broccoli Crown,Banana,0.315484,0.007050
8,4,produce,9387,24852,Granny Smith Apples,Banana,0.314721,0.003308
9,4,produce,9839,13176,Organic Broccoli,Bag of Organic Bananas,0.317604,0.004001
10,4,produce,10749,13176,Organic Red Bell Pepper,Bag of Organic Bananas,0.262850,0.004794
11,4,produce,11777,24852,Red Raspberries,Banana,0.294039,0.003346
12,4,produce,15290,24852,Orange Bell Pepper,Banana,0.261266,0.003712
13,4,produce,16759,13176,Organic Carrot Bunch,Bag of Organic Bananas,0.266935,0.003544
14,4,produce,16797,24852,Strawberries,Banana,0.299969,0.014847
15,4,produce,19057,13176,Organic Large Extra Fancy Fuji Apple,Bag of Organic Bananas,0.336562,0.007416
16,4,produce,20114,26209,Jalapeno Peppers,Limes,0.288046,0.004169
17,4,produce,21137,13176,Organic Strawberries,Bag of Organic Bananas,0.282174,0.023428
18,4,produce,22825,13176,Organic D'Anjou Pears,Bag of Organic Bananas,0.319070,0.004603
19,4,produce,22825,21137,Organic D'Anjou Pears,Organic Strawberries,0.252509,0.003643
20,4,produce,24184,24852,Red Peppers,Banana,0.288468,0.006387
21,4,produce,26209,47626,Limes,Large Lemon,0.264379,0.012156
22,4,produce,27521,13176,Organic Lacinato (Dinosaur) Kale,Bag of Organic Bananas,0.257808,0.003460
23,4,produce,27966,13176,Organic Raspberries,Bag of Organic Bananas,0.320952,0.013566
24,4,produce,27966,21137,Organic Raspberries,Organic Strawberries,0.301118,0.012728
25,4,produce,28199,24852,"Clementines, Bag",Banana,0.315291,0.003552
26,4,produce,28204,24852,Organic Fuji Apple,Banana,0.371508,0.009222
27,4,produce,28842,26209,Bunched Cilantro,Limes,0.290625,0.004253
28,4,produce,29487,24852,Roma Tomato,Banana,0.292883,0.004359
29,4,produce,30391,13176,Organic Cucumber,Bag of Organic Bananas,0.274875,0.009664
30,4,produce,31717,26209,Organic Cilantro,Limes,0.285593,0.007675
31,4,produce,34969,24852,Red Vine Tomato,Banana,0.265891,0.004527
32,7,beverages,35221,44632,Lime Sparkling Water,Sparkling Water Grapefruit,0.256867,0.003849
33,4,produce,37646,13176,Organic Gala Apples,Bag of Organic Bananas,0.288359,0.006173
34,4,produce,39275,21137,Organic Blueberries,Organic Strawberries,0.255538,0.009672
35,4,produce,39877,13176,Organic Granny Smith Apple,Bag of Organic Bananas,0.278134,0.004954
36,4,produce,39928,13176,Organic Kiwi,Bag of Organic Bananas,0.347872,0.004984
37,4,produce,39928,21137,Organic Kiwi,Organic Strawberries,0.275000,0.003940
38,4,produce,41787,24852,Bartlett Pears,Banana,0.386081,0.003552
39,4,produce,41950,13176,Organic Tomato Cluster,Bag of Organic Bananas,0.250197,0.004840
40,4,produce,43961,24852,Organic Peeled Whole Baby Carrots,Banana,0.262602,0.004923
41,4,produce,45066,24852,Honeycrisp Apple,Banana,0.346663,0.009382
42,4,produce,46906,24852,Grape White/Green Seedless,Banana,0.263261,0.003064
43,4,produce,47209,13176,Organic Hass Avocado,Bag of Organic Bananas,0.331825,0.018444
44,4,produce,47626,24852,Large Lemon,Banana,0.265274,0.016447
45,4,produce,47766,24852,Organic Avocado,Banana,0.299096,0.016889
46,4,produce,49683,24852,Cucumber Kirby,Banana,0.307915,0.005663

In [122]:
df3.to_csv('B.csv')